### ISSUE TITLE
Missing processed test data file 

### ISSUE THREAD

**Issue by hugochan** [amritasaha1812/CSQA_Code#11]
Hi,

Could you please tell me where to download the processed test data files? I didn't find it in README. Thank you so much!

**Comment by vardaan123** [comment]
Ideally, for test data the users are expected to pre-process it themselves using the script https://github.com/amritasaha1812/CSQA_Code/blob/master/prepare_data_for_hred.py. But we shall make it available here soon.

**Comment by hugochan** [comment]
@vardaan123 I see. Yes, it would be very helpful if you can make this available. 
I tried to process test data using the script you mentioned, but I got the following error with pylucene:  `Format version is not supported...  This version of Lucene only supports indexes created with release 6.0 and later.`
Which version of pylucene is supposed to be used here? I am using pylucene 7.2. And this is the only version of pylucene I was able to successfully install on my MacBook.

**Comment by vardaan123** [comment]
Issue resolved via email.
