### ISSUE TITLE
Lucene index no longer supported

### ISSUE THREAD

**Issue by dungtn** [amritasaha1812/CSQA_Code#13]
Hi @amritasaha1812,

I'm trying to replicate the experiments and I have this error: 

`org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(SimpleFSIndexInput(path="/Users/dthai/Codes/csqa-rl/CSQA_Code/lucene_index_9m/segments_1"))): 3 (needs to be between 6 and 9). This version of Lucene only supports indexes created with release 6.0 and later.`

Can you share the code to generate Lucene index or upload the generated index of the newer version?

Thank you!

**Comment by yaoleo** [comment]
I met the same problem. how to fix it?@dungtn @amritasaha1812 

Thank you!

**Comment by amritasaha1812** [comment]
Hi... please use this code to create lucene index https://github.com/amritasaha1812/CSQA_Code/blob/master/createLuceneIndex.py, for newer versions you might have to edit this code.

**Comment by yaoleo** [comment]
Thank  you. 
RE-INSTALL pylucene-4.10.1-1 is useful.
