### ISSUE TITLE
"id_entity_map.pickle" File not found in wikidata_dir

### ISSUE THREAD

**Issue by sanyam5** [amritasaha1812/CSQA_Code#4]
the wikidata_dir does not contain the file being loaded on this line. 
https://github.com/amritasaha1812/CSQA_Code/blob/master/run_model.py#L314

**Comment by sanyam5** [comment]
Seem's like the location was wrong. I have created a pull request to fix this.

https://github.com/amritasaha1812/CSQA_Code/pull/5

**Comment by amritasaha1812** [comment]
pushed with the fix. Please check now

**Comment by sanyam5** [comment]
Hi @amritasaha1812 I am getting a lot of import errors in LuceneSearch.py. The following seem to be native java libraries how do you import them?

```
from java.io import File
from org.apache.lucene.analysis.standard import StandardAnalyzer
from org.apache.lucene.index import DirectoryReader, IndexReader
from org.apache.lucene.index import Term
from org.apache.lucene.search import BooleanClause, BooleanQuery, PhraseQuery, TermQuery
from org.apache.lucene.queryparser.classic import QueryParser
from org.apache.lucene.store import SimpleFSDirectory
from org.apache.lucene.search import IndexSearcher
from org.apache.lucene.util import Version
```

Do you use some java wrappers?

**Comment by amritasaha1812** [comment]
u'll need to install pylucene. But since i have provided the pkl files (i will shortly upload the pkl file for the test data also) for now u can comment out these lines. It should work properly if it finds the pkl files in the proper place

**Comment by sanyam5** [comment]
I have already installed pylucene. But I still get the error at the line 
`from java.io import File` as it cannot find any module named `java.io`.

As you said, for now I will comment and use the .pkl files but I would also be interested to run this code end to end.

UPDATE: Turns out I was using an older version of pylucene. Upgrading it to 6.4.1 did the trick!
